### ISSUE TITLE
Fix Static Assets handling

### ISSUE THREAD

**Issue by LarsGJobloop** [NordikE/Favourite-Beers#1]
https://github.com/NordikE/Favourite-Beers/blob/7d6c45979ffa8381c555a27dedf3430ee3e289ba/src/BeerInfo.js#L1-L12

What you have done here works (ish). But if you where looking in the terminal the first time you did this you probably saw a quite a bit of yellow text (warnings).

There are two ways to fix this, and make your code more correct.

1. Keep the images in the public folder, and use absolute paths strings for referencing them rather then using Vite to import the file path. (This works due to how Vite is copying the content of the `public` directory over into the `dist` (distribution) output folder when building).

Going from what you have now to:
```javascript
export const BeerInfo = [
  {
    id: 1,
    name: "Aegir Minus",
    image: "/assets/AegirMinus.jpg",
  },
]
```

2. Move the images back into the `src/assets` directory and update where you are importing them from lik

```javascript
import aegirMinusImage from "./assets/AegirMinus.jpg"

export const BeerInfo = [
  {
    id: 1,
    name: "Aegir Minus",
    image: aegirMinusImage,
  },
]
```

Both are viable approaches. If you want to read more on how ViteJS is handling these Static Assets and the difference between the two approaches you can look at [the documentation here](https://vitejs.dev/guide/assets#the-public-directory).

**Comment by NordikE** [comment]
Fixed.
