### ISSUE TITLE
Remove modules that are import as part of the global scope

### ISSUE THREAD

**Issue by LarsGJobloop** [NordikE/Favourite-Beers#3]
https://github.com/NordikE/Favourite-Beers/blob/7d6c45979ffa8381c555a27dedf3430ee3e289ba/src/App.jsx#L1C1-L1C31

In new versions of React >= 17, we don't have to import React to use it, it's done automatically in all *.jsx/*.tsx files.
It also makes ESLint complain that we have defined but unused variables in our code, which would cause breakage of a linting check in any Continous Integration pipelines that could be running.

I suggest to just remove the line.

**Comment by NordikE** [comment]
Deleted.
